# Generated by Django 5.2.4 on 2025-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('ar', 'العربية')], default='en', max_length=2),
        ),
    ]
