# Generated by Django 5.2.5 on 2025-09-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_add_current_location_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='location_lng',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer')], default='transfer', max_length=20),
        ),
    ]
