# Generated by Django 5.2.5 on 2025-08-31 15:04

import apps.risk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('bank_account_number', models.CharField(default=apps.risk.models.generate_random_8digit, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('home_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('home_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_known_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_known_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('avg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('std_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('params', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Threshold',
                'verbose_name_plural': 'Thresholds',
            },
        ),
    ]
