# Generated by Django 5.2.5 on 2025-08-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('params_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('home_lat', models.FloatField(blank=True, null=True)),
                ('home_lng', models.FloatField(blank=True, null=True)),
                ('avg_amount', models.FloatField(default=0)),
                ('std_amount', models.FloatField(default=1)),
                ('last_known_lat', models.FloatField(blank=True, null=True)),
                ('last_known_lng', models.FloatField(blank=True, null=True)),
                ('device_fingerprint_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('currency', models.CharField(default='TND', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='risk.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_iban', models.CharField(max_length=34)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='TND', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('ALLOWED', 'ALLOWED'), ('CHALLENGE', 'CHALLENGE'), ('BLOCKED', 'BLOCKED'), ('EXECUTED', 'EXECUTED')], default='PENDING', max_length=10)),
                ('risk_score', models.IntegerField(default=0)),
                ('decision_reason', models.JSONField(default=list)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='risk.account')),
            ],
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signals_json', models.JSONField(default=dict)),
                ('rules_triggered', models.JSONField(default=list)),
                ('decision', models.CharField(choices=[('ALLOW', 'ALLOW'), ('STEP_UP', 'STEP_UP'), ('BLOCK', 'BLOCK')], max_length=10)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_event', to='risk.transaction')),
            ],
        ),
    ]
