# Generated by Django 5.2.5 on 2025-08-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='riskevent',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='riskevent',
            name='transaction',
        ),
        migrations.AlterModelOptions(
            name='threshold',
            options={'verbose_name': 'Threshold', 'verbose_name_plural': 'Thresholds'},
        ),
        migrations.AddField(
            model_name='threshold',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='RiskEvent',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
