# Generated by Django 5.2.5 on 2025-09-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avg_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average transaction amount in DZD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance in Algerian Dinar (DZD)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='std_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation of transaction amounts in DZD', max_digits=14),
        ),
    ]
