# Generated by Django 5.2.5 on 2025-09-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_alter_clientprofile_avg_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
